# Required items.
game: "Assassin's Creed Odyssey"
api: 1
steamID: 812140
uid: com.thegreatcabbage.acodyssey
author: TheGreatCabbage
packageName: acodyssey
features:
  - graphics

# Optional items.
graphicsConfig: "$!DOCUMENTS!$/Assassin's Creed Odyssey/ACOdyssey.ini"
gameDirectory: "Assassin's Creed Odyssey"
verificationPaths:
  - ACOdyssey.exe